# Generated by Django 5.2 on 2025-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bucketpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
