# Generated by Django 5.2 on 2025-07-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_message_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
    ]
