# Generated by Django 5.2 on 2025-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_album_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bucketpoint",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
